version: "3"

services:
  db:
    image: "postgres:11"
    ports:
      - 5432:5432
    restart: always
    env_file:
      - database.env

  demoproject:
    image: demoapp
    env_file:
      - demosite.env
    ports:
      - 8000:80
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: ${AWSLOG_GROUP}
    depends_on:
      - db
